name: lambert
description: Lambert coordinates convertion package
version: 1.0.0
author: Yannick Heinrich <yannick.heinrich@gmail.com>
homepage: https://github.com/yageek/lambert-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0 