name: lambert
description: Lambert coordinates convertion package
version: 0.0.1
author: Yannick Heinrich <yannick.heinrich@gmail.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
